version: '3'

services:
  node-red:
    image: nodered/node-red:latest
    ports:
      - "1880:1880"
    volumes:
      - ./node-red/data:/data
      - ./cert:/cert
    environment:
      - TZ=America/Toronto